apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "glauth.fullname" . }}
  labels:
    app: {{ template "glauth.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "glauth.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "glauth.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ include "glauth.image" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
{{- range $port := .Values.service.ports }}
        - containerPort: {{ $port.internal }}
{{- end }}
        command: ["/app/glauth", "-c", "/app/config/config.cfg"]
        livenessProbe:
          exec:
            command:
            - sh
            - "-c"
            - "echo OK"
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
{{- if eq (.Values.persistence.enabled | toString) "true" }}
        - name: {{ .Chart.Name }}-data
          mountPath: /app/config
        - name: {{ .Chart.Name }}-config
          mountPath: /app/config/config.cfg
          subPath: config.cfg
{{- else }}
        - name: {{ .Chart.Name }}-config
          mountPath: /app/config
          readOnly: true
{{- end }}
{{- with .Values.backend.tls }}
        - name: {{ $.Chart.Name }}-tls
          mountPath: {{ .mountPath }}
          readOnly: true
{{- end }}
        readinessProbe:
          exec:
            command:
            - sh
            - "-c"
            - "echo OK"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
{{- if eq (.Values.persistence.enabled | toString) "true" }}
  {{- if .Values.persistence.existingClaim }}
      - name: {{ .Chart.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
  {{- else }}
      - name: {{ .Chart.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-data
  {{- end }}
{{- else }}
{{- end }}
      - name: {{ .Chart.Name }}-config
        secret:
          secretName: glauth-config
{{- with .Values.backend.tls }}
      - name: {{ $.Chart.Name }}-tls
        secret:
          secretName: {{ .secretName }}
{{- end }}
