apiVersion: v1
kind: Secret
metadata:
  name: glauth-config
stringData:
{{- if .Values.backend.file }}
  config.cfg: |-
{{- .Values.config.file | nindent 4 }}
{{- else if eq .Values.backend.type "config" }}
  config.cfg: |-
{{ .Files.Get "config/sample-simple.cfg" | indent 4 }}
{{- else if eq .Values.backend.type "database" }}
  config.cfg: |-
{{ .Files.Get "config/sample-database.cfg" | indent 4 }}
{{- end }}
