apiVersion: v1
kind: Service
metadata:
  name: {{ template "glauth.fullname" . }}
  labels:
    name: {{ template "glauth.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "glauth.fullname" . }}
  ports:
{{- with .Values.service.ldap }}
  - name: ldap
    port: {{ .port }}
    targetPort: {{ .targetport }}
{{- if eq $.Values.service.type "NodePort" }}
    nodePort: {{ .nodeport }}
{{- end }}
    protocol: TCP
{{- end }}
{{- with .Values.service.ldaps }}
  - name: ldaps
    port: {{ .port }}
    targetPort: {{ .targetport }}
{{- if eq $.Values.service.type "NodePort" }}
    nodePort: {{ .nodeport }}
{{- end }}
    protocol: TCP
{{- end }}
{{- with .Values.service.web }}
  - name: web
    port: {{ .port }}
    targetPort: {{ .targetport }}
{{- if eq $.Values.service.type "NodePort" }}
    nodePort: {{ .nodeport }}
{{- end }}
    protocol: TCP
{{- end }}
